config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/xtclimmine:
      branch: main
      repo: https://github.com/PalomoIFCA/xtclimmine
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/xtclimmine git:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-cerulean-fox.sh
        container: qc.acc_stealthy-cyan-oyster
  QC.Doc:
    repos:
      github.com/PalomoIFCA/xtclimmine find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-brown-fossa.sh
        container: qc.doc_skimpy-sepia-whippet
      github.com/PalomoIFCA/xtclimmine git:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-corn-lemur.sh
        container: qc.doc_chewy-emerald-moose
      github.com/PalomoIFCA/xtclimmine markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-sapphire-bird.sh
        container: qc.doc_greasy-goldenrod-mongoose
  QC.Lic:
    repos:
      github.com/PalomoIFCA/xtclimmine licensee:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-denim-bison.sh
        container: qc.lic_queasy-periwinkle-hedgehog
  QC.Met:
    repos:
      github.com/PalomoIFCA/xtclimmine validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-orchid-salamander.sh
        container: qc.met_snoopy-eggplant-earwig
  QC.Sec:
    repos:
      github.com/PalomoIFCA/xtclimmine bandit:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-amber-wolf.sh
        container: qc.sec_messy-eggplant-raccoon
  QC.Sty:
    repos:
      github.com/PalomoIFCA/xtclimmine flake8:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-charcoal-greyhound.sh
        container: qc.sty_frumpy-wisteria-cichlid
      github.com/PalomoIFCA/xtclimmine hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.homey-ultramarine-dogfish.sh
        container: qc.sty_nippy-pear-sponge
      github.com/PalomoIFCA/xtclimmine jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.beady-sangria-cow.sh
        container: qc.sty_lumpy-heliotrope-emu
  QC.Uni:
    repos:
      github.com/PalomoIFCA/xtclimmine pytest:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-mustard-capuchin.sh
        container: qc.uni_wheezy-crimson-bobcat
  QC.Ver:
    repos:
      github.com/PalomoIFCA/xtclimmine get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-azure-salamander.sh
        container: qc.ver_muzzy-indigo-kakapo
timeout: 5400
