config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/xtclimmine:
      branch: main
      repo: https://github.com/PalomoIFCA/xtclimmine
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/xtclimmine git:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-teal-kakapo.sh
        container: qc.acc_flaky-lilac-macaw
  QC.Doc:
    repos:
      github.com/PalomoIFCA/xtclimmine find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-celadon-walrus.sh
        container: qc.doc_skanky-linen-hare
      github.com/PalomoIFCA/xtclimmine git:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-pink-elephant.sh
        container: qc.doc_lumpy-green-beaver
      github.com/PalomoIFCA/xtclimmine markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-harlequin-tapir.sh
        container: qc.doc_cranky-ruby-wildebeest
  QC.Lic:
    repos:
      github.com/PalomoIFCA/xtclimmine licensee:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-scarlet-barnacle.sh
        container: qc.lic_tacky-asparagus-akita
  QC.Met:
    repos:
      github.com/PalomoIFCA/xtclimmine validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-orchid-wasp.sh
        container: qc.met_nippy-pumpkin-zebu
  QC.Sec:
    repos:
      github.com/PalomoIFCA/xtclimmine bandit:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-persimmon-robin.sh
        container: qc.sec_bluesy-plum-spitz
  QC.Sty:
    repos:
      github.com/PalomoIFCA/xtclimmine flake8:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-pumpkin-chamois.sh
        container: qc.sty_ready-aqua-quetzal
      github.com/PalomoIFCA/xtclimmine hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-linen-rottweiler.sh
        container: qc.sty_crabby-violet-wombat
      github.com/PalomoIFCA/xtclimmine jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-green-stoat.sh
        container: qc.sty_cozy-orchid-husky
  QC.Uni:
    repos:
      github.com/PalomoIFCA/xtclimmine pytest:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-platinum-mist.sh
        container: qc.uni_chummy-cardinal-nightingale
  QC.Ver:
    repos:
      github.com/PalomoIFCA/xtclimmine get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-harlequin-cichlid.sh
        container: qc.ver_woozy-xanthic-birman
timeout: 5400
