config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/xtclimmine:
      branch: main
      repo: https://github.com/PalomoIFCA/xtclimmine
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/xtclimmine git:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-asparagus-ibis.sh
        container: qc.acc_grumpy-denim-bandicoot
  QC.Doc:
    repos:
      github.com/PalomoIFCA/xtclimmine find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-russet-coral.sh
        container: qc.doc_slimy-razzmatazz-sloth
      github.com/PalomoIFCA/xtclimmine git:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-heliotrope-meerkat.sh
        container: qc.doc_shabby-tan-ragdoll
      github.com/PalomoIFCA/xtclimmine markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-yellow-loon.sh
        container: qc.doc_cloudy-chocolate-bordeaux
  QC.Lic:
    repos:
      github.com/PalomoIFCA/xtclimmine licensee:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-khaki-harrier.sh
        container: qc.lic_lumpy-jade-dormouse
  QC.Met:
    repos:
      github.com/PalomoIFCA/xtclimmine validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-tangerine-argentino.sh
        container: qc.met_cheeky-chartreuse-setter
  QC.Sec:
    repos:
      github.com/PalomoIFCA/xtclimmine bandit:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-amethyst-newt.sh
        container: qc.sec_slimy-fuchsia-wolfhound
  QC.Sty:
    repos:
      github.com/PalomoIFCA/xtclimmine flake8:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-azure-vulture.sh
        container: qc.sty_lumpy-cyan-mammoth
      github.com/PalomoIFCA/xtclimmine hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-yellow-swan.sh
        container: qc.sty_sloppy-persimmon-husky
      github.com/PalomoIFCA/xtclimmine jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-rose-termite.sh
        container: qc.sty_muzzy-ecru-gecko
  QC.Uni:
    repos:
      github.com/PalomoIFCA/xtclimmine pytest:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-rose-mau.sh
        container: qc.uni_blurry-puce-bordeaux
  QC.Ver:
    repos:
      github.com/PalomoIFCA/xtclimmine get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-razzmatazz-swan.sh
        container: qc.ver_flimsy-charcoal-molly
timeout: 5400
