config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/xtclimmine:
      branch: main
      repo: https://github.com/PalomoIFCA/xtclimmine
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/xtclimmine git:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-amaranth-flamingo.sh
        container: qc.acc_cranky-olivine-cat
  QC.Doc:
    repos:
      github.com/PalomoIFCA/xtclimmine find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-saffron-badger.sh
        container: qc.doc_dorky-lilac-flamingo
      github.com/PalomoIFCA/xtclimmine git:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-lavender-forest.sh
        container: qc.doc_dorky-corn-wrasse
      github.com/PalomoIFCA/xtclimmine markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-teal-binturong.sh
        container: qc.doc_sleazy-lemon-serval
  QC.Lic:
    repos:
      github.com/PalomoIFCA/xtclimmine licensee:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-teal-llama.sh
        container: qc.lic_frumpy-orange-nightingale
  QC.Met:
    repos:
      github.com/PalomoIFCA/xtclimmine validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-heliotrope-pinscher.sh
        container: qc.met_leaky-ecru-beagle
  QC.Sec:
    repos:
      github.com/PalomoIFCA/xtclimmine bandit:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-grey-monkey.sh
        container: qc.sec_boozy-thistle-mayfly
  QC.Sty:
    repos:
      github.com/PalomoIFCA/xtclimmine flake8:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-amethyst-caiman.sh
        container: qc.sty_grumpy-khaki-moth
      github.com/PalomoIFCA/xtclimmine hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-gold-abyssinian.sh
        container: qc.sty_skinny-pumpkin-millipede
      github.com/PalomoIFCA/xtclimmine jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-olivine-magpie.sh
        container: qc.sty_nippy-copper-frise
  QC.Uni:
    repos:
      github.com/PalomoIFCA/xtclimmine pytest:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-scarlet-earwig.sh
        container: qc.uni_gimpy-ruby-collie
  QC.Ver:
    repos:
      github.com/PalomoIFCA/xtclimmine get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-orchid-robin.sh
        container: qc.ver_woolly-aquamarine-forest
timeout: 5400
