config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/xtclimmine:
      branch: main
      repo: https://github.com/PalomoIFCA/xtclimmine
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/xtclimmine git:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-blue-greyhound.sh
        container: qc.acc_lovely-jade-abyssinian
  QC.Doc:
    repos:
      github.com/PalomoIFCA/xtclimmine find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-viridian-fox.sh
        container: qc.doc_beady-ruby-termite
      github.com/PalomoIFCA/xtclimmine git:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-saffron-sponge.sh
        container: qc.doc_muggy-gold-wolf
      github.com/PalomoIFCA/xtclimmine markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-mustard-shrew.sh
        container: qc.doc_lousy-amber-sparrow
  QC.Lic:
    repos:
      github.com/PalomoIFCA/xtclimmine licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-thistle-gar.sh
        container: qc.lic_trippy-wheat-gecko
  QC.Met:
    repos:
      github.com/PalomoIFCA/xtclimmine validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-ivory-owl.sh
        container: qc.met_clammy-rose-woodpecker
  QC.Sec:
    repos:
      github.com/PalomoIFCA/xtclimmine bandit:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-plum-fox.sh
        container: qc.sec_seedy-rust-frigatebird
  QC.Sty:
    repos:
      github.com/PalomoIFCA/xtclimmine flake8:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-coral-pinscher.sh
        container: qc.sty_leaky-buff-badger
      github.com/PalomoIFCA/xtclimmine hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-mustard-tamarin.sh
        container: qc.sty_sleepy-bronze-paradise
      github.com/PalomoIFCA/xtclimmine jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-khaki-dogfish.sh
        container: qc.sty_stinky-seashell-wolverine
  QC.Uni:
    repos:
      github.com/PalomoIFCA/xtclimmine pytest:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-buff-rottweiler.sh
        container: qc.uni_zippy-champagne-seahorse
  QC.Ver:
    repos:
      github.com/PalomoIFCA/xtclimmine get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-orchid-hummingbird.sh
        container: qc.ver_fuzzy-cinnabar-loon
timeout: 5400
