config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/xtclimmine:
      branch: main
      repo: https://github.com/PalomoIFCA/xtclimmine
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/xtclimmine git:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-purple-tang.sh
        container: qc.acc_scaly-peach-crane
  QC.Doc:
    repos:
      github.com/PalomoIFCA/xtclimmine find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-olivine-scorpion.sh
        container: qc.doc_sickly-cornflower-albatross
      github.com/PalomoIFCA/xtclimmine git:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-olivine-clam.sh
        container: qc.doc_greasy-cerulean-chinchilla
      github.com/PalomoIFCA/xtclimmine markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-pear-angelfish.sh
        container: qc.doc_boozy-pear-gibbon
  QC.Lic:
    repos:
      github.com/PalomoIFCA/xtclimmine licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-seashell-wildebeest.sh
        container: qc.lic_flabby-ecru-leopard
  QC.Met:
    repos:
      github.com/PalomoIFCA/xtclimmine validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-razzmatazz-dunker.sh
        container: qc.met_sleazy-aquamarine-ant
  QC.Sec:
    repos:
      github.com/PalomoIFCA/xtclimmine bandit:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-indigo-dragonfly.sh
        container: qc.sec_ugly-wheat-albatross
  QC.Sty:
    repos:
      github.com/PalomoIFCA/xtclimmine flake8:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-indigo-wolf.sh
        container: qc.sty_sleazy-carmine-wrasse
      github.com/PalomoIFCA/xtclimmine hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-russet-woodpecker.sh
        container: qc.sty_breezy-cinnabar-kudu
      github.com/PalomoIFCA/xtclimmine jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-khaki-angelfish.sh
        container: qc.sty_paltry-white-civet
  QC.Uni:
    repos:
      github.com/PalomoIFCA/xtclimmine pytest:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-blue-urchin.sh
        container: qc.uni_cheeky-mauve-tzu
  QC.Ver:
    repos:
      github.com/PalomoIFCA/xtclimmine get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-myrtle-horse.sh
        container: qc.ver_woozy-crimson-blue
timeout: 5400
