config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/xtclimmine:
      branch: main
      repo: https://github.com/PalomoIFCA/xtclimmine
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/xtclimmine git:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-crimson-catfish.sh
        container: qc.acc_breezy-pink-oriole
  QC.Doc:
    repos:
      github.com/PalomoIFCA/xtclimmine find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-maroon-bee.sh
        container: qc.doc_crappy-periwinkle-dunker
      github.com/PalomoIFCA/xtclimmine git:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-carmine-rabbit.sh
        container: qc.doc_foggy-rose-mongrel
      github.com/PalomoIFCA/xtclimmine markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-white-tarsier.sh
        container: qc.doc_pretty-cinnamon-vole
  QC.Lic:
    repos:
      github.com/PalomoIFCA/xtclimmine licensee:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-fuchsia-chameleon.sh
        container: qc.lic_lovely-white-oriole
  QC.Met:
    repos:
      github.com/PalomoIFCA/xtclimmine validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-linen-spitz.sh
        container: qc.met_homely-grey-moose
  QC.Sec:
    repos:
      github.com/PalomoIFCA/xtclimmine bandit:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-black-okapi.sh
        container: qc.sec_geeky-saffron-hedgehog
  QC.Sty:
    repos:
      github.com/PalomoIFCA/xtclimmine flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-sangria-hippopotamus.sh
        container: qc.sty_sleazy-olive-woodpecker
      github.com/PalomoIFCA/xtclimmine hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-wisteria-dogfish.sh
        container: qc.sty_lumpy-goldenrod-eagle
      github.com/PalomoIFCA/xtclimmine jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-cinnabar-frog.sh
        container: qc.sty_seedy-rust-weasel
  QC.Uni:
    repos:
      github.com/PalomoIFCA/xtclimmine pytest:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-viridian-tortoise.sh
        container: qc.uni_breezy-charcoal-jackal
  QC.Ver:
    repos:
      github.com/PalomoIFCA/xtclimmine get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-coral-wolfhound.sh
        container: qc.ver_chummy-gamboge-spider
timeout: 5400
