config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/xtclimmine:
      branch: notebook_integration
      repo: https://github.com/PalomoIFCA/xtclimmine
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/xtclimmine git:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-maroon-badger.sh
        container: qc.acc_homey-white-falcon
  QC.Doc:
    repos:
      github.com/PalomoIFCA/xtclimmine find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-scarlet-affenpinscher.sh
        container: qc.doc_hasty-amaranth-dragon
      github.com/PalomoIFCA/xtclimmine git:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-seashell-bear.sh
        container: qc.doc_muzzy-alizarin-uguisu
      github.com/PalomoIFCA/xtclimmine markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-cerise-vole.sh
        container: qc.doc_chewy-wheat-gharial
  QC.Lic:
    repos:
      github.com/PalomoIFCA/xtclimmine licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-denim-swan.sh
        container: qc.lic_lumpy-gold-elephant
  QC.Met:
    repos:
      github.com/PalomoIFCA/xtclimmine validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-vermilion-panda.sh
        container: qc.met_sickly-fuchsia-anteater
  QC.Sec:
    repos:
      github.com/PalomoIFCA/xtclimmine bandit:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-violet-russel.sh
        container: qc.sec_homey-lavender-cheetah
  QC.Sty:
    repos:
      github.com/PalomoIFCA/xtclimmine flake8:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-zucchini-flounder.sh
        container: qc.sty_sunny-bronze-ostrich
      github.com/PalomoIFCA/xtclimmine hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-puce-mongoose.sh
        container: qc.sty_zippy-fuchsia-bear
      github.com/PalomoIFCA/xtclimmine jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-brass-echidna.sh
        container: qc.sty_snappy-purple-hummingbird
  QC.Uni:
    repos:
      github.com/PalomoIFCA/xtclimmine pytest:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-goldenrod-shark.sh
        container: qc.uni_scaly-yellow-sheep
  QC.Ver:
    repos:
      github.com/PalomoIFCA/xtclimmine get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-lavender-spaniel.sh
        container: qc.ver_cranky-taupe-gopher
timeout: 5400
