config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/xtclimmine:
      branch: main
      repo: https://github.com/PalomoIFCA/xtclimmine
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/xtclimmine git:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-lemon-olm.sh
        container: qc.acc_dorky-corn-opossum
  QC.Doc:
    repos:
      github.com/PalomoIFCA/xtclimmine find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-purple-alligator.sh
        container: qc.doc_snoopy-razzmatazz-buzzard
      github.com/PalomoIFCA/xtclimmine git:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-purple-stingray.sh
        container: qc.doc_grumpy-celadon-angelfish
      github.com/PalomoIFCA/xtclimmine markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-olive-iguana.sh
        container: qc.doc_jumpy-denim-rhinoceros
  QC.Lic:
    repos:
      github.com/PalomoIFCA/xtclimmine licensee:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-tangerine-woodlouse.sh
        container: qc.lic_scanty-aquamarine-weasel
  QC.Met:
    repos:
      github.com/PalomoIFCA/xtclimmine validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.silly-silver-cat.sh
        container: qc.met_skinny-cyan-dog
  QC.Sec:
    repos:
      github.com/PalomoIFCA/xtclimmine bandit:
        commands:
        - /usr/bin/env sh .sqa/script.surly-plum-donkey.sh
        container: qc.sec_surly-mustard-sheep
  QC.Sty:
    repos:
      github.com/PalomoIFCA/xtclimmine flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-cerise-bee.sh
        container: qc.sty_stealthy-grey-mule
      github.com/PalomoIFCA/xtclimmine hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-teal-markhor.sh
        container: qc.sty_bumpy-sepia-ant
      github.com/PalomoIFCA/xtclimmine jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-aquamarine-squirrel.sh
        container: qc.sty_muzzy-ivory-gopher
  QC.Uni:
    repos:
      github.com/PalomoIFCA/xtclimmine pytest:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-magnolia-javanese.sh
        container: qc.uni_frumpy-white-javanese
  QC.Ver:
    repos:
      github.com/PalomoIFCA/xtclimmine get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-teal-octopus.sh
        container: qc.ver_tacky-magenta-fossa
timeout: 5400
